"""Framework-neutral DeepEyes dataset source identities."""

from __future__ import annotations


DEEPEYES_VSTAR_SOURCE = "vstar"
DEEPEYES_ARXIVQA_SOURCE = "arxivqa"
DEEPEYES_TEACHER_SOURCE = "teacher"
DEEPEYES_THINKLITE_SOURCE = "thinklite"

VISUAL_SOURCES = frozenset(
    {
        DEEPEYES_VSTAR_SOURCE,
        DEEPEYES_ARXIVQA_SOURCE,
        DEEPEYES_TEACHER_SOURCE,
    }
)
VISUAL_SOURCES_WITH_GT_REGIONS = frozenset({DEEPEYES_VSTAR_SOURCE})
VISUAL_SOURCES_WITHOUT_GT_REGIONS = VISUAL_SOURCES - VISUAL_SOURCES_WITH_GT_REGIONS


__all__ = [
    "DEEPEYES_ARXIVQA_SOURCE",
    "DEEPEYES_TEACHER_SOURCE",
    "DEEPEYES_THINKLITE_SOURCE",
    "DEEPEYES_VSTAR_SOURCE",
    "VISUAL_SOURCES",
    "VISUAL_SOURCES_WITH_GT_REGIONS",
    "VISUAL_SOURCES_WITHOUT_GT_REGIONS",
]
