"""Native Qwen TGVF tool protocol."""

from .parser import StrictToolCallParser
from .native import NativeProtocolRenderer, RenderedTranscript
from .schema import (
    ParseErrorCode,
    ParsedImageZoomInCall,
    ParsedToolCall,
    NativeToolCall,
    SampledAssistantTurn,
    IMAGE_ZOOM_IN_TOOL_NAME,
    IMAGE_ZOOM_IN_TOOL_SCHEMA,
    IMAGE_ZOOM_IN_TOOL_SCHEMA_CANONICAL_JSON,
    IMAGE_ZOOM_IN_TOOL_SCHEMA_SHA256,
    POLICY_RL_TOOL_NAMES,
    TGVF_FOCUS_TOOL_NAME,
    TGVF_FOCUS_TOOL_SCHEMA,
    TGVF_FOCUS_TOOL_SCHEMA_CANONICAL_JSON,
    TGVF_FOCUS_TOOL_SCHEMA_SHA256,
    TOOL_CALL_CLOSE,
    TOOL_CALL_OPEN,
    TargetSpan,
    TerminationReason,
    TextOffsets,
    TokenByteSpan,
    ToolCallParseError,
    build_image_zoom_in_tool_schema,
    build_native_tool_schemas,
    build_tgvf_focus_tool_schema,
    native_tool_set_sha256,
)
from .state_machine import (
    AgentEvent,
    AgentEventType,
    AgentPhase,
    AgentState,
    InvalidTransitionError,
    MultiCallStateMachine,
    TransitionResult,
)

__all__ = [
    "AgentEvent",
    "AgentEventType",
    "AgentPhase",
    "AgentState",
    "InvalidTransitionError",
    "MultiCallStateMachine",
    "NativeProtocolRenderer",
    "ParseErrorCode",
    "ParsedImageZoomInCall",
    "ParsedToolCall",
    "NativeToolCall",
    "SampledAssistantTurn",
    "RenderedTranscript",
    "StrictToolCallParser",
    "IMAGE_ZOOM_IN_TOOL_NAME",
    "IMAGE_ZOOM_IN_TOOL_SCHEMA",
    "IMAGE_ZOOM_IN_TOOL_SCHEMA_CANONICAL_JSON",
    "IMAGE_ZOOM_IN_TOOL_SCHEMA_SHA256",
    "POLICY_RL_TOOL_NAMES",
    "TGVF_FOCUS_TOOL_NAME",
    "TGVF_FOCUS_TOOL_SCHEMA",
    "TGVF_FOCUS_TOOL_SCHEMA_CANONICAL_JSON",
    "TGVF_FOCUS_TOOL_SCHEMA_SHA256",
    "TOOL_CALL_CLOSE",
    "TOOL_CALL_OPEN",
    "TargetSpan",
    "TerminationReason",
    "TextOffsets",
    "TokenByteSpan",
    "ToolCallParseError",
    "TransitionResult",
    "build_image_zoom_in_tool_schema",
    "build_native_tool_schemas",
    "build_tgvf_focus_tool_schema",
    "native_tool_set_sha256",
]
