"""Optional exact-latent vLLM bridge; importing it does not require vLLM."""

from .live_client import (
    SamplingParamsFactory,
    VLLMLivePolicyTurnClient,
    VLLMLivePromptInputs,
    VLLMLivePromptInputsPort,
    VLLMTokenByteSpanDecoderPort,
)

from .packer import (
    QWEN3_DEEPSTACK_BRANCH_COUNT,
    QWEN3_DEEPSTACK_BRANCH_LAYERS,
    PackedQwen3ImageItem,
    PackedQwen3Replay,
    pack_qwen3_vllm_observation,
    pack_qwen3_vllm_replay,
    pack_qwen3_vllm_replay_bundle,
)
from .observation_resolver import Qwen3VLLMObservationPayloadResolver
from .registration import (
    SUPPORTED_VLLM_VERSION,
    SUPPORTED_VLLM_VERSIONS,
    TGVF_QWEN3_VLLM_ARCHITECTURE,
    TGVF_VLLM_ATTENTION_BACKEND,
    TGVF_VLLM_MM_ENCODER_ATTN_BACKEND,
    VLLMCompatibilityError,
    VLLMPluginError,
    VLLMPluginRegistration,
    VLLMPublicPluginAPI,
    VLLMUnavailableError,
    load_vllm_public_plugin_api,
    register_tgvf_qwen3_vllm_plugin,
    vllm_is_available,
)
from .sampler import (
    VLLM_POLICY_TURN_REQUEST_SCHEMA,
    VLLM_POLICY_TURN_RESPONSE_SCHEMA,
    VLLM_PROCESSED_LOGPROBS_MODE,
    VLLMOutputDecodingContract,
    VLLMPolicySampler,
    VLLMPolicyTurnClient,
    VLLMPolicyTurnRequest,
    VLLMPolicyTurnResponse,
    VLLMRequestContextIdentityPort,
    VLLMTerminationOutcome,
    VLLMTokenLogprob,
    VLLMTurnRNGIdentity,
    VLLMTurnRNGPort,
    VLLMTurnTerminationContract,
)
from .turn_runtime import (
    ContentAddressedVLLMTurnRNG,
    FastTokenizerTokenByteSpanDecoder,
    LiveVLLMTurnContextRegistry,
    TURN_CONTEXT_SCHEMA,
    TURN_RNG_SCHEMA,
    VLLMObservationPayloadResolver,
    VLLMResolvedObservationPayload,
    prompt_token_ids_sha256,
)

__all__ = [
    "QWEN3_DEEPSTACK_BRANCH_COUNT",
    "QWEN3_DEEPSTACK_BRANCH_LAYERS",
    "ContentAddressedVLLMTurnRNG",
    "FastTokenizerTokenByteSpanDecoder",
    "LiveVLLMTurnContextRegistry",
    "SUPPORTED_VLLM_VERSION",
    "SUPPORTED_VLLM_VERSIONS",
    "TGVF_QWEN3_VLLM_ARCHITECTURE",
    "TGVF_VLLM_ATTENTION_BACKEND",
    "TGVF_VLLM_MM_ENCODER_ATTN_BACKEND",
    "TURN_CONTEXT_SCHEMA",
    "TURN_RNG_SCHEMA",
    "PackedQwen3ImageItem",
    "PackedQwen3Replay",
    "Qwen3VLLMObservationPayloadResolver",
    "SamplingParamsFactory",
    "VLLMCompatibilityError",
    "VLLMLivePolicyTurnClient",
    "VLLMLivePromptInputs",
    "VLLMLivePromptInputsPort",
    "VLLMOutputDecodingContract",
    "VLLMObservationPayloadResolver",
    "VLLMPolicySampler",
    "VLLMPolicyTurnClient",
    "VLLMPolicyTurnRequest",
    "VLLMPolicyTurnResponse",
    "VLLMPluginError",
    "VLLMPluginRegistration",
    "VLLMPublicPluginAPI",
    "VLLMRequestContextIdentityPort",
    "VLLMResolvedObservationPayload",
    "VLLMTerminationOutcome",
    "VLLMTokenLogprob",
    "VLLMTokenByteSpanDecoderPort",
    "VLLMTurnRNGIdentity",
    "VLLMTurnRNGPort",
    "VLLMTurnTerminationContract",
    "VLLMUnavailableError",
    "VLLM_POLICY_TURN_REQUEST_SCHEMA",
    "VLLM_POLICY_TURN_RESPONSE_SCHEMA",
    "VLLM_PROCESSED_LOGPROBS_MODE",
    "load_vllm_public_plugin_api",
    "pack_qwen3_vllm_observation",
    "pack_qwen3_vllm_replay",
    "pack_qwen3_vllm_replay_bundle",
    "prompt_token_ids_sha256",
    "register_tgvf_qwen3_vllm_plugin",
    "vllm_is_available",
]
