"""Optional external judge boundary."""

from .base import (
    DisabledJudgeProvider,
    JudgeProvider,
    JudgeRequest,
    JudgeResult,
    JudgeUsage,
)
from .dispatch import (
    JUDGE_DISPATCH_MAXIMUM_CONCURRENCY,
    JUDGE_DISPATCH_SCHEMA_VERSION,
    BoundedJudgeDispatcher,
    JudgeDispatchConfig,
    JudgeDispatchMode,
    JudgeModelRoute,
)
from .openai_compatible import (
    BoundOpenAICompatibleJudge,
    JUDGE_SAMPLE_FAILURE_ABORT,
    JUDGE_SAMPLE_FAILURE_ZERO,
    JudgeSampleFailureError,
    OpenAICompatibleJudgeConfig,
    OpenAICompatibleJudgeProvider,
    QWEN25_72B_RL_JUDGE_PROMPT_VERSION,
    QWEN25_72B_RL_JUDGE_SYSTEM_PROMPT,
    load_openai_compatible_judge,
)
from .tgvf_visual_quality import (
    BoundTGVFVisualQualityJudge,
    TGVF_VISUAL_QUALITY_JUDGE_CONFIG_VERSION,
    TGVF_VISUAL_QUALITY_JUDGE_PROMPT_VERSION,
    TGVF_VISUAL_QUALITY_JUDGE_SYSTEM_PROMPT,
    TGVFVisualQualityFailureKind,
    TGVFVisualQualityJudgeConfig,
    TGVFVisualQualityJudgeProvider,
    TGVFVisualQualityJudgeRequest,
    TGVFVisualQualityJudgeResult,
    load_tgvf_visual_quality_judge,
    tgvf_visual_quality_prompt_identity,
)

__all__ = [
    "DisabledJudgeProvider",
    "JudgeProvider",
    "JudgeRequest",
    "JudgeResult",
    "JudgeUsage",
    "JUDGE_DISPATCH_MAXIMUM_CONCURRENCY",
    "JUDGE_DISPATCH_SCHEMA_VERSION",
    "BoundedJudgeDispatcher",
    "JudgeDispatchConfig",
    "JudgeDispatchMode",
    "JudgeModelRoute",
    "BoundOpenAICompatibleJudge",
    "JUDGE_SAMPLE_FAILURE_ABORT",
    "JUDGE_SAMPLE_FAILURE_ZERO",
    "JudgeSampleFailureError",
    "OpenAICompatibleJudgeConfig",
    "OpenAICompatibleJudgeProvider",
    "QWEN25_72B_RL_JUDGE_PROMPT_VERSION",
    "QWEN25_72B_RL_JUDGE_SYSTEM_PROMPT",
    "load_openai_compatible_judge",
    "BoundTGVFVisualQualityJudge",
    "TGVF_VISUAL_QUALITY_JUDGE_CONFIG_VERSION",
    "TGVF_VISUAL_QUALITY_JUDGE_PROMPT_VERSION",
    "TGVF_VISUAL_QUALITY_JUDGE_SYSTEM_PROMPT",
    "TGVFVisualQualityFailureKind",
    "TGVFVisualQualityJudgeConfig",
    "TGVFVisualQualityJudgeProvider",
    "TGVFVisualQualityJudgeRequest",
    "TGVFVisualQualityJudgeResult",
    "load_tgvf_visual_quality_judge",
    "tgvf_visual_quality_prompt_identity",
]
